### ISSUE TITLE
comment에서 postId를 찾을 수 없음

### ISSUE THREAD

**Issue by pengin7384** [mash-up-kr/Boilerplate_TypeScript_MySQL#5]
![image](https://user-images.githubusercontent.com/32831939/107070708-04e40e00-6827-11eb-9926-6e4f05b51af2.png)
POST /post/:postId/comments로 등록하고 디비를 보니 postId가 null로 채워져있는 거 같습니다!

**Comment by swimjiy** [comment]
확인해보니 `comment.service.ts` 파일의 `addComment()` 메서드에서 `comment`를 추가할 때 `post`를 실질적으로 연결해주는 코드가 없어서 NULL로 뜨는 것 같습니다.

따라서 [typeorm 공식 문서](https://github.com/typeorm/typeorm/blob/master/docs/many-to-one-one-to-many-relations.md) 를 토대로 아래와 같이 코드를 수정했을 때 정상적으로 `postId`가 나타났습니다.

다만 완벽한 해결책은 아닐 수 있으므로 더 좋은 방법이 있다면 코멘트 남겨주시길 바랍니다.

```typescript
export async function addComment(postId: number, content: string) {
  const comment: Comment = new Comment();
  // 수정한 코드
  const post: Post = await Post.findOne({id: postId});
  comment.post = post;
  // 기존 코드
  // Post.id = postId;
  comment.content = content;
  await comment.save();
  return comment;
}
```

**Comment by god9599** [comment]
확인했습니다 감사합니다!

추가적인 방법이 있는 지 확인해보겠습니다~
